services:
  mcp-server:
    build: .
    cap_drop:
      - all
    deploy:
      restart_policy:
        condition: any
        delay: 5s
    environment:
      - BRAVE_API_KEY
    init: true
    ports:
      - 8080:8080
    security_opt:
      - no-new-privileges:true
