apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: brave-search-mcp-backend-config
  namespace: mcp
spec:
  timeoutSec: 30
  connectionDraining:
    drainingTimeoutSec: 60
  logging:
    enable: true
    sampleRate: 1.0
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /ping
    port: 8080