apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - backendconfig.yaml

commonLabels:
  project: brave-search-mcp
  environment: production
  managed-by: kustomize

images:
  - name: ghcr.io/memenow/brave-search-mcp
    newTag: latest